apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: store-cart-mfe-mf
  name: store-cart-mfe-mf
spec:
  ports:
  - name: "30003"
    port: 30003
    targetPort: 30003
    nodePort: 30003
  selector:
    io.kompose.service: store-cart-mfe-mf
  type: NodePort
status:
  loadBalancer: {}
