apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: store-purchase-mfe-mf
  name: store-purchase-mfe-mf
spec:
  ports:
  - name: "30004"
    port: 30004
    targetPort: 30004
    nodePort: 30004
  selector:
    io.kompose.service: store-purchase-mfe-mf
  type: NodePort
status:
  loadBalancer: {}
