apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: store-cart-service
  name: store-cart-service
spec:
  ports:
  - name: "30006"
    port: 30006
    targetPort: 80
    nodePort: 30006
  selector:
    io.kompose.service: store-cart-service
  type: NodePort
status:
  loadBalancer: {}
