apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: store-navbar-mfe-mf
  name: store-navbar-mfe-mf
spec:
  ports:
  - name: "30002"
    port: 30002
    targetPort: 30002
    nodePort: 30002
  selector:
    io.kompose.service: store-navbar-mfe-mf
  type: NodePort
status:
  loadBalancer: {}
