apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: store-catalog-mfe-mf
  name: store-catalog-mfe-mf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: store-catalog-mfe-mf
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: D:\kompose\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: store-catalog-mfe-mf
    spec:
      containers:
      - image: ricsilva/mfe-store-catalog-mf
        imagePullPolicy: ""
        name: store-catalog-mfe-mf
        ports:
        - containerPort: 30000
        resources: {}
        stdin: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
