apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: store-app-shell-mf
  name: store-app-shell-mf
spec:
  ports:
  - name: "30001"
    port: 30001
    targetPort: 30001
    nodePort: 30001
  selector:
    io.kompose.service: store-app-shell-mf
  type: NodePort
status:
  loadBalancer: {}
